### ISSUE TITLE
install the package

### ISSUE THREAD

**Issue by ykzzyk** [Felix-Petersen/gendr#2]
Hello, thanks for the work!

I tried to install the package on windows and linux with the cuda version matched my local installation. But i don't seem to successfully compile the cuda files and I got error
```
    1 error detected in the compilation of "E:/GitHub/gendr/gendr/cuda/generalized_renderer_cuda_kernel.cu".
    generalized_renderer_cuda_kernel.cu
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "D:\miniconda3\envs\gendr\lib\site-packages\torch\utils\cpp_extension.py", line 1900, in _run_ninja_build
        subprocess.run(
      File "D:\miniconda3\envs\gendr\lib\subprocess.py", line 528, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "E:\GitHub\gendr\setup.py", line 36, in <module>
        setup(
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\__init__.py", line 107, in setup
        return distutils.core.setup(**attrs)
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
        return run_commands(dist)
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
        dist.run_commands()
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\dist.py", line 1234, in run_command
        super().run_command(command)
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\command\develop.py", line 34, in run
        self.install_for_development()
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\command\develop.py", line 111, in install_for_development
        self.run_command('build_ext')
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\dist.py", line 1234, in run_command
        super().run_command(command)
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
        cmd_obj.run()
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
        _build_ext.run(self)
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
        self.build_extensions()
      File "D:\miniconda3\envs\gendr\lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions
        build_ext.build_extensions(self)
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
        self._build_extensions_serial()
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
        self.build_extension(ext)
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
        _build_ext.build_extension(self, ext)
      File "D:\miniconda3\envs\gendr\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
        objects = self.compiler.compile(
      File "D:\miniconda3\envs\gendr\lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "D:\miniconda3\envs\gendr\lib\site-packages\torch\utils\cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "D:\miniconda3\envs\gendr\lib\site-packages\torch\utils\cpp_extension.py", line 1916, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    [end of output]
```
when i install the package on Windows. I used the command pip install .
I also tried pip install gendr, it does not work as well. Can you provide some help for me to install and try the package?

Thanks!

**Comment by Felix-Petersen** [comment]
I cannot speak for support on Windows, as I only operate on linux, but the following document from another CUDA package that I published might help with installation on linux: https://github.com/Felix-Petersen/difflogic/blob/main/INSTALLATION_SUPPORT.md

In the output you provided, it looks like `ninja` does not exist on your windows installation. 

Wrt. linux, it is usually important that the PyTorch CUDA version exactly matches the (sub)version you get from `nvcc -v`. In some cases, it also works with around 1 subversion of CUDA difference. And one other issue could be that only CUDA but not CUDA Toolkit is installed, e.g., that `nvcc` is missing.
